apiVersion: apps/v1
kind: Deployment
metadata:
  name: secretapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secretapp
  template:
    metadata:
      labels:
        app: secretapp
    spec:
      serviceAccountName: secretsa
      containers:
      - name: chaosfy
        image: neosam01/secretflaskapp:v3
        ports:
        - containerPort: 8989
