apiVersion: v1
kind: Service
metadata:
  name: secretapp-service
spec:
  type: LoadBalancer  # Type of service
  selector:
    app: secretapp  # Matches the app label from deployment
  ports:
    - protocol: TCP
      port: 7272          # External port (you will access the app on this port)
      targetPort: 8989  # Port that the Flask app is listening on
